export const DOUBT_LIST_REQUEST = "DOUBT_LIST_REQUEST";
export const DOUBT_LIST_SUCCESS = "DOUBT_LIST_SUCCESS";
export const DOUBT_LIST_FAIL = "DOUBT_LIST_FAIL";

export const DOUBT_CREATE_REQUEST = "DOUBT_CREATE_REQUEST";
export const DOUBT_CREATE_SUCCESS = "DOUBT_CREATE_SUCCESS";
export const DOUBT_CREATE_FAIL = "DOUBT_CREATE_FAIL";

export const DOUBT_UPDATE_REQUEST = "DOUBT_UPDATE_REQUEST";
export const DOUBT_UPDATE_SUCCESS = "DOUBT_UPDATE_SUCCESS";
export const DOUBT_UPDATE_FAIL = "DOUBT_UPDATE_FAIL";

export const DOUBT_DELETE_REQUEST = "DOUBT_DELETE_REQUEST";
export const DOUBT_DELETE_SUCCESS = "DOUBT_DELETE_SUCCESS";
export const DOUBT_DELETE_FAIL = "DOUBT_DELETE_FAIL";

export const DOUBT_TEACHER_LIST_REQUEST = "DOUBT_TEACHER_LIST_REQUEST";
export const DOUBT_TEACHER_LIST_SUCCESS = "DOUBT_TEACHER_LIST_SUCCESS";
export const DOUBT_TEACHER_LIST_FAIL = "DOUBT_TEACHER_LIST_FAIL";
