export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_SOLUTION_REQUEST = "POST_SOLUTION_REQUEST";
export const POST_SOLUTION_SUCCESS = "POST_SOLUTION_SUCCESS";
export const POST_SOLUTION_FAIL = "POST_SOLUTION_FAIL";

export const POST_QUERY_REQUEST = "POST_QUERY_REQUEST";
export const POST_QUERY_SUCCESS = "POST_QUERY_SUCCESS";
export const POST_QUERY_FAIL = "POST_QUERY_FAIL";
