export const STUDENT_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const STUDENT_LOGOUT = "USER_LOGOUT";

export const STUDENT_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const STUDENT_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const STUDENT_UPDATE_REQUEST = "USER_REGISTER_REQUEST";
export const STUDENT_UPDATE_SUCCESS = "USER_REGISTER_SUCCESS";
export const STUDENT_UPDATE_FAIL = "USER_REGISTER_FAIL";
